# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 23:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rent', models.IntegerField()),
                ('image', models.ImageField(upload_to='imagesHouses/')),
                ('name', models.CharField(max_length=100, verbose_name='Название:')),
                ('describe', models.CharField(max_length=150, verbose_name='Описание:')),
            ],
        ),
        migrations.CreateModel(
            name='AddImage2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='imagesHouses/')),
            ],
        ),
        migrations.CreateModel(
            name='AutoPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_quick_payment', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('id_rent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.CharField(max_length=100)),
                ('user_login', models.CharField(max_length=50)),
                ('date_comment', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='CommentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user_about', models.IntegerField()),
                ('id_user_from', models.IntegerField()),
                ('text_comment', models.CharField(max_length=50)),
                ('date_comment', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=10)),
                ('currency_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DonePenalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe_penalty', models.CharField(max_length=150)),
                ('id_user_for', models.IntegerField()),
                ('size_penalty', models.FloatField()),
                ('id_done_rent', models.IntegerField()),
                ('is_payd', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DoneRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_house', models.IntegerField()),
                ('id_user_owner', models.IntegerField()),
                ('id_user_renter', models.IntegerField()),
                ('date_rent', models.DateField(default=None)),
                ('cost', models.CharField(max_length=50)),
                ('next_payment_date', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='LogOperationsBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('type_operation', models.CharField(max_length=50)),
                ('describe_operation', models.CharField(max_length=100)),
                ('date_operation', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatusRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user_from', models.IntegerField()),
                ('login_user_from', models.CharField(max_length=50, null=True)),
                ('id_user_to', models.IntegerField()),
                ('creation_date', models.DateField(default=None)),
                ('text_message', models.CharField(max_length=100)),
                ('text_more', models.CharField(max_length=100)),
                ('id_rent', models.IntegerField(null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Monetization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe_mon', models.CharField(max_length=100)),
                ('value_mon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Penalties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_penalty', models.CharField(max_length=50)),
                ('describe_penalty', models.CharField(max_length=100)),
                ('cost_penalty', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='QuickPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_payment', models.CharField(default=None, max_length=50)),
                ('amount', models.IntegerField(default=None)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TOFI.DoneRent')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название:')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес:')),
                ('min_rent_time', models.IntegerField(verbose_name='Срок аренды:')),
                ('area', models.IntegerField(verbose_name='Площадь:')),
                ('payment_interval',
                 models.IntegerField(blank=True, default=None, null=True, verbose_name='Срок оплаты')),
                ('date_of_construction', models.IntegerField(default=None, verbose_name='Год строительства:')),
                ('creation_date', models.DateField(default=None)),
                ('other', models.CharField(max_length=100, verbose_name='Другое:')),
                ('cost', models.CharField(max_length=50, verbose_name='Цена аренды:')),
                ('user_login', models.CharField(max_length=50, null=True)),
                ('status_rent', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(max_length=16, verbose_name='Номер карты/Card number')),
                ('period_validity', models.CharField(max_length=5, verbose_name='Срок действия (ММГГ)')),
                ('name_card_owner', models.CharField(max_length=50, verbose_name='Имя держателя карты')),
                ('CVC2_CVV', models.CharField(max_length=3, verbose_name='CVC2/CVV')),
                ('size', models.FloatField(verbose_name='Баланс')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('passport_id', models.CharField(max_length=50, verbose_name='Номер паспорта')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('email', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('taxpayer_account_number', models.IntegerField(null=True, verbose_name='УНН')),
                ('license_field', models.CharField(max_length=50, null=True, verbose_name='Лицензия')),
                ('ie', models.BooleanField(default=False, verbose_name='ИП')),
                ('balance', models.FloatField(default=0, verbose_name='')),
                ('is_active', models.BooleanField(default=True)),
                ('reason_block', models.CharField(max_length=100, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_moder', models.BooleanField(default=False)),
                ('user_card_id', models.ManyToManyField(default=None, to='TOFI.UserCard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quickpayment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
