# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0002_remove_rent_payment_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='payment_interval',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Срок оплаты'),
        ),
    ]
