# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0003_remove_myuser_roleid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='LastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='PassportID',
            new_name='passport_id',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='Surname',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
