# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0006_auto_20161215_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autopayment',
            old_name='id_quick_payment',
            new_name='quick_payment',
        ),
    ]
