# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0009_auto_20161117_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='license_field',
            field=models.CharField(max_length=50, verbose_name='Лицензия'),
        ),
    ]
