# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0009_donerent_payed_until_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donerent',
            name='payed_until_time',
            field=models.FloatField(default=0),
        ),
    ]
