# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 22:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0010_auto_20161216_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donerent',
            name='id_user_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
