# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0012_auto_20161117_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='Area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='Cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='CreationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='DateOfConstruction',
            new_name='min_rent_time',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='Other',
            new_name='other',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='MinRentTime',
        ),
        migrations.AddField(
            model_name='rent',
            name='date_of_construction',
            field=models.DateField(default=None),
        ),
    ]
