# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 22:25
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0012_auto_20161217_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donerent',
            name='id_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TOFI.Rent'),
        ),
    ]
