# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0013_auto_20161217_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickpayment',
            name='amount',
            field=models.FloatField(default=None),
        ),
    ]
