# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0013_auto_20161117_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='creation_date',
            field=models.DateField(default=None),
        ),
    ]
