# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0015_auto_20161122_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='balance',
            field=models.FloatField(null=True),
        ),
    ]
