# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-19 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0015_auto_20161219_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(max_length=50, unique=True, verbose_name='Электронная почта'),
        ),
    ]
