# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0008_auto_20161220_1024'),
        ('TOFI', '0016_auto_20161220_0136'),
    ]

    operations = [
    ]
