# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0016_myuser_balance'),
        ('TOFI', '0015_auto_20161117_1519'),
    ]

    operations = [
    ]
