# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 23:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0017_merge_20161124_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(max_length=16, verbose_name='Номер карты/Card number')),
                ('period_validity', models.CharField(max_length=5, verbose_name='Срок действия (ММГГ)')),
                ('name_card_owner', models.CharField(max_length=50, verbose_name='Имя держателя карты')),
                ('CVC2_CVV', models.CharField(max_length=3, verbose_name='CVC2/CVV')),
                ('size', models.IntegerField(verbose_name='Баланс')),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='balance',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='usercard',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
