# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-21 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0017_merge_20161220_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.IntegerField()),
                ('number_key', models.IntegerField()),
                ('key', models.IntegerField()),
            ],
        ),
    ]
