# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0017_merge_20161220_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.IntegerField()),
                ('number_key', models.IntegerField()),
                ('key', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='donerent',
            name='id_house',
        ),
        migrations.RemoveField(
            model_name='donerent',
            name='id_user_owner',
        ),
        migrations.RemoveField(
            model_name='quickpayment',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='quickpayment',
            name='username',
        ),
        migrations.DeleteModel(
            name='DoneRent',
        ),
    ]
