# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0018_auto_20161126_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='user_id',
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_card_id',
            field=models.ManyToManyField(to='TOFI.UserCard'),
        ),
    ]
