# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 21:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0019_auto_20161221_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickpayment',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TOFI.DoneRent'),
        ),
        migrations.AlterField(
            model_name='quickpayment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
