# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0019_auto_20161126_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_card_id',
            field=models.ManyToManyField(default=None, to='TOFI.UserCard'),
        ),
    ]
