# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0020_auto_20161221_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='donerent',
            name='fine',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='donerent',
            name='next_auto_payment_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='donerent',
            name='payed',
            field=models.FloatField(default=0),
        ),
    ]
