# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0020_auto_20161126_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStatusRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user_from', models.IntegerField()),
                ('id_user_to', models.IntegerField()),
                ('creation_date', models.DateField(default=None)),
                ('text_message', models.CharField(max_length=100)),
                ('text_more', models.CharField(max_length=100)),
            ],
        ),
    ]
