# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0021_auto_20161221_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donerent',
            name='next_auto_payment_date',
        ),
        migrations.RemoveField(
            model_name='donerent',
            name='payed',
        ),
    ]
