# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0021_messagestatusrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestatusrent',
            name='login_user_from',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
