# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0022_auto_20161221_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestatusrent',
            name='type_mes',
            field=models.BooleanField(default=True),
        ),
    ]
