# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0023_messagestatusrent_is_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.CharField(max_length=100)),
                ('user_login', models.CharField(max_length=50)),
            ],
        ),
    ]
