# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0019_auto_20161221_2229'),
        ('TOFI', '0023_messagestatusrent_type_mes'),
    ]

    operations = [
    ]
