# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0024_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_comment',
            field=models.DateField(default=None),
        ),
    ]
