# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0024_merge_20161221_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddImage',
        ),
        migrations.DeleteModel(
            name='AddImage2',
        ),
    ]
