# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0025_comment_date_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestatusrent',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rent',
            name='status_rent',
            field=models.BooleanField(default=True),
        ),
    ]
