# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0026_auto_20161226_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickpayment',
            name='user_payment',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
