# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0026_auto_20161201_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestatusrent',
            name='id_rent',
            field=models.IntegerField(null=True),
        ),
    ]
