# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0027_messagestatusrent_id_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_house', models.IntegerField()),
                ('id_user_owner', models.IntegerField()),
                ('id_user_renter', models.IntegerField()),
                ('date_rent', models.DateField(default=None)),
                ('cost', models.CharField(max_length=50)),
                ('pay_number', models.IntegerField()),
                ('paid_user', models.IntegerField()),
            ],
        ),
    ]
