# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0027_auto_20161226_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logoperationsbalance',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
