# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-26 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0028_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='describe',
            field=models.CharField(default=5, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='id_rent',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='TOFI.Rent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
