# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0028_donerent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogOperationsBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('type_operation', models.CharField(max_length=50)),
                ('describe_operation', models.CharField(max_length=100)),
                ('date_operation', models.DateField(default=None)),
            ],
        ),
    ]
