# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0029_logoperationsbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user_about', models.IntegerField()),
                ('id_user_from', models.IntegerField()),
                ('text_comment', models.CharField(max_length=50)),
                ('date_comment', models.DateField(default=None)),
            ],
        ),
    ]
