# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TOFI', '0030_auto_20161227_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='passport_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер паспорта'),
        ),
    ]
