# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0031_myuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='reason_block',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
