# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0032_myuser_reason_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TOFI.DoneRent')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
