# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0033_quickpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickpayment',
            name='is_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quickpayment',
            name='user_card',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
