# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0034_auto_20161205_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quickpayment',
            old_name='user_card',
            new_name='user_payment',
        ),
        migrations.RemoveField(
            model_name='quickpayment',
            name='is_balance',
        ),
    ]
