# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0039_auto_20161206_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
    ]
