# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0040_remove_myuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_moder',
            field=models.BooleanField(default=False),
        ),
    ]
