# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0042_penalties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адрес:'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='area',
            field=models.IntegerField(verbose_name='Площадь:'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='cost',
            field=models.CharField(max_length=50, verbose_name='Цена аренды:'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_of_construction',
            field=models.IntegerField(default=None, verbose_name='Год строительства:'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='min_rent_time',
            field=models.IntegerField(verbose_name='Срок аренды:'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название:'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='other',
            field=models.CharField(max_length=100, verbose_name='Другое:'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='user_login',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
