# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0044_monetization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='balance',
            field=models.FloatField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='size',
            field=models.FloatField(verbose_name='Баланс'),
        ),
    ]
