# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0045_auto_20161208_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonePenalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe_penalty', models.CharField(max_length=150)),
                ('id_user_for', models.IntegerField()),
                ('size_penalty', models.IntegerField()),
                ('id_done_rent', models.IntegerField()),
                ('is_payd', models.BooleanField(default=False)),
            ],
        ),
    ]
