# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0048_addimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddImage2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='imagesHouses/')),
            ],
        ),
        migrations.AlterField(
            model_name='addimage',
            name='describe',
            field=models.CharField(max_length=150, verbose_name='Описание:'),
        ),
        migrations.AlterField(
            model_name='addimage',
            name='image',
            field=models.ImageField(upload_to='imagesHouses/'),
        ),
        migrations.AlterField(
            model_name='addimage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название:'),
        ),
    ]
