# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0049_auto_20161212_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_quick_payment', models.IntegerField()),
            ],
        ),
    ]
