# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOFI', '0050_autopayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopayment',
            name='id_rent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autopayment',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
